# Generated by Django 5.1.7 on 2025-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('datetime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('sender_currency', models.CharField(choices=[('gbp', 'GBP'), ('eur', 'EUR'), ('usd', 'USD')], default='GBP', max_length=3)),
                ('recipient_currency', models.CharField(choices=[('gbp', 'GBP'), ('eur', 'EUR'), ('usd', 'USD')], default='GBP', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
