# Generated by Django 5.1.7 on 2025-03-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
