# Generated by Django 5.1.7 on 2025-03-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
