# Generated by Django 5.1.7 on 2025-03-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('currency', models.CharField(choices=[('gbp', 'GBP'), ('eur', 'EUR'), ('usd', 'USD')], max_length=3)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
