# Generated by Django 4.1.5 on 2023-01-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visit_date', models.DateField(verbose_name='visit date')),
                ('comment_str', models.CharField(max_length=500)),
            ],
        ),
    ]
